$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules/**
  - public/locales/**
  - src/@types/**
  - "public/assets/**"
dictionaryDefinitions:
  - name: en-words
    path: ./src/config/cspell/en/words.txt
    description: custom dictionary for english words
    addWords: true
  - name: vi-words
    path: ./src/config/cspell/vi/words.txt
    description: custom dictionary for vietnamese words
    addWords: true
dictionaries: ["en-words", "vi-words"]
language: "en,vi"
files:
  - "./src/**/*.{js,jsx,ts,tsx,json,md,mdx,html,css,scss,less}"

cache:
  cacheFormat: legacy
  cacheStrategy: metadata
  useCache: true
  cacheLocation: ".cspellcache"

languageSettings:
  - allowCompoundWords: false
    caseSensitive: false
    enabled: true
    languageId: "typescript, typescriptreact, javascript, javascriptreact"
  - allowCompoundWords: false
    caseSensitive: true
    enabled: true
    languageId: json
enabled: true
