// Generated by https://quicktype.io

export type PersonalTaxModel = {
  result: string
  detail?: string
  data: Data
}

type Data = {
  companyName: string
  internationalName: string
  abbreviatedName: string
  taxCode: string
  address: string
  country: string
  province: string
  district: string
  commune: string
  street: string
  legalRepresentative: string
  dateOfOperation: string
  link: string
  source: string
  phone?: string
  businesses: Array<Business>
  position?: string
  gender?: string
  legalDocumentType?: string
  legalDocumentValue?: string
  issueDate?: string
  placeOfIssue?: string
  permanentAddress?: string
  email?: string
  managedBy?: string
  registrationPlace?: string
  charteredCapital?: string
  businessType?: string
  status?: string
  businessLine: BusinessLine
}

type BusinessLine = {
  businessLineCode: string
  businessLineDetail: string
}

type Business = {
  businessCode: string
  name: string
  createdAt: string
  updatedAt: string
}
